version: '3.8'
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: projectdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://user:password@db:5432/projectdb
      SECRET_KEY: 'YOUR_SECRET_KEY'
      ALGORITHM: 'HS256'
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    ports:
      - '8000:8000'
    volumes:
      - media:/app/media

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - back

volumes:
  postgres_data:
  media:
